version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: proplus-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: proplus-app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MONGO_URL=${MONGO_URL:-mongodb://mongo:27017}
      - MONGO_DB=${MONGO_DB:-proplus}
      - JWT_SECRET=${JWT_SECRET:-change_me_super_secret}
      - JWT_EXPIRES_MIN=${JWT_EXPIRES_MIN:-60}
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    volumes:
      - .:/app
volumes:
  mongo_data:
