version: "3.9"

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: proplus_app
    depends_on:
      - mongo
    environment:
      # .env-ը ներսում էլ ունես, բայց ENV-երը compose-ից էլ տալը հարմար է
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB=proplus
      - MONGO_COLLECTION=finance
      - REPORTS_DIR=/app/data_analytics/reports
    volumes:
      # Քո automation կոդը live mount, որ փոխես՝ ներսում էլ տեսնի
      - ./automation:/app/automation
      - ./data_analytics/reports:/app/data_analytics/reports
    working_dir: /app/automation
    command: bash
    tty: true

volumes:
  mongo_data:

services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - MONGO_DB=proplus
      - JWT_SECRET=change_me_super_secret
      - JWT_EXPIRES_MIN=60
    ports:
      - "8000:8000"
    depends_on:
      - mongo

volumes:
  mongo_data:

version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: proplus-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: proplus-app
    restart: unless-stopped
    env_file: ../.env
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    volumes:
      - ../:/app

volumes:
  mongo_data:
